### ISSUE TITLE
Lack of necessary documentation

### ISSUE THREAD

**Issue by liangdebao** [niosus/MDP-Solver#1]
According to the format given in [script.m], the main program runs roughly as follows:solve_mdp('global_parkings_graph.dat', 'log_5_12_2013_parkings_graph.dat', 10, 4, 20, 'log_5_12_14__params_10_4_20_real', 0)
But I failed to find a proper "log_5_12_14__params_10_4_20_real",I wonder how I can get this,780164114@qq.com,looking forward to your reply,thank you!

**Comment by niosus** [comment]
Hey @liangdebao 
Sorry, but this code was really never of good quality and was just means to an end to solve the problem at hand and to prove that it is theoretically possible to do so. However, this code is on GitHub for convenience only and I don't intend to support it and to make any documentation available. Sorry about that.
